### PR TITLE
Feature: Decoration Overhaul

### LINKED ISSUE #36: Support multiple file highlighting
This will be in a post-1.0+ release. We should support high lighting and searching throughout multiple files.
We should be able to drop down the occurrences tab and see a similar result for search.

### LINKED ISSUE #88: Improve performance
Hi — I'm trying this plugin out and am finding it to be substantially more fickle than the other RegExp highlighters I've used. 

Two things I'm noticing a lot are (1) that the highlight does not show up until the cursor has moved past a pattern, and (2) that there can be highlight artifacts after a pattern no longer exists.

Here's a couple examples. I have highlights on `model` and `empir`. In the first screenshot, I've typed `model` and the cursor is at the `l`, but the highlight has not appeared. 

CleanShot 2024-07-13 at 02 39 44@2x

In the second screenshot the cursor is actually a space past the the end of the word and the highlight still hasn't appeared (this behavior is less common but does occur). 

CleanShot 2024-07-13 at 02 36 37@2x

In the third, I've deleted `empir` but the border is still being drawn on the place where the pattern started.

CleanShot 2024-07-13 at 02 36 00@2x

Plugin is off to to great start!

### PR DESCRIPTION
**Pull request by stneveadomi**
This pull request will entail all the work needed to overhaul the decoration system and ideally improve time and space complexity. This is intended to close #88 and fortunately, close #36.

There will still need to be work done to support multiple file searching for occurrences, but the remaining occurrence tab will only reflect the active text editor (the tab that is focused).

This overhaul has been a bit of a PITA, but is making steady progress. I will note bugs here as I go through and manually test all flows.

### CODE REVIEW

**Comment by stneveadomi** [comment]
Known issues:

- [ ] Changing regex does not immediately update decorations

**Comment by stneveadomi** [comment]
Manual Testing Checklist:

- [ ] Do rules apply as expected?
- [ ] Does rule priority work as expected?
- [ ] Do multi-line rules apply as expected?
- [ ] Does enabling/disabling a rule work?
- [ ] Does drag and drop work?
- [ ] Does drag and drop cause decorations to propagate?
- [ ] No ghosting of decorations (a rule is showing that shouldn't)?
- [ ] Does writing in a document look good and rules not broken?
- [ ] Does writing at an intersection of a rule (within a match) work and not broken?
- [ ] Do rules persist when creating a rule and closing the webview (via the drop down).
- [ ] On start up, does creating a rule persist? (Open VS Code, run command create a rule, open grepc sidebar, check).
- [ ] Closing and reopening local and workspace rules should not change any states of the rules.


Right Click Commands / Drop Down Commands (ensure that the rules work that these produce)  

- [ ] Create a blank rule (follow various paths from dropdowns e.g. cancel create, only enter some values, etc)
- [ ] Create a rule from selection (follow various paths from dropdowns e.g. cancel create, only enter some values, etc)
- [ ] Disable all rules
- [ ] Disable global rules
- [ ] DIsable local rules
- [ ] Enable all rules
- [ ] Enable workspace rules
- [ ] Enable global rules

Commands Only (Ctrl + P, type grepc)  

- [ ] Check release notes page

**Comment by cheljur** [comment]
Sorry I went through this so late, travel was a bit busier than
anticipated. Just to go through the list below:

   - Strike through == passed
   - Bold == there's an issue
   - No font == i left a question cause I wasn't sure to test or I'm
   finally crashing

The main thing I noticed is that the priority is definitely off. For
example, the local "cat" rule has lower priority than the "grey cat" global
rule, but the "this" global rule has lower priority than the "multi line"
rule? Let me know if that's a red herring or expected. Also have an example
where priority doesn't seem to update in the test list below.
[image: image.png]

I've also noticed that the rules don't get applied to new text
automatically, unless I toggle the rules. Let me know if this is expected
or a bug.

I somehow triggered weird highlighting that doesn't apply to any of my
rules:
[image: image.png]

Test Results:

   - Do rules apply as expected?
   - * Does rule priority work as expected?*
      - Priority is def broken
      - [image: image.png]
      - [image: image.png]
      -  Do multi-line rules apply as expected?
      - is this what's meant by multi line?
      - [image: image.png]
      -  Does enabling/disabling a rule work? Yee
   -  Does drag and drop work?
   -  Does drag and drop cause decorations to propagate?
      - not sure if I follow
   -  No ghosting of decorations (a rule is showing that shouldn't)?
      - no sure if I follow
   - * Does writing in a document look good and rules not broken?*
      - looks like rule not apply to new text, need to toggle rule (line 6)
      - [image: image.png]
      -  Does writing at an intersection of a rule (within a match) work
   and not broken?
      - looks right? (line 6)
      - [image: image.png]
      -  Do rules persist when creating a rule and closing the webview (via
   the drop down).
      - rule stays when i close "local" and "global" rules
      - [image: image.png]
      -  On start up, does creating a rule persist? (Open VS Code, run
   command create a rule, open grepc sidebar, check).
      - looking good on start up
         - [image: image.png]
         - created "what is love" via right click and persists
         - [image: image.png]
         -  Closing and reopening local and workspace rules should not
   change any states of the rules.

Right Click Commands / Drop Down Commands (ensure that the rules work that
these produce)

   -  Create a blank rule (follow various paths from dropdowns e.g. cancel
   create, only enter some values, etc)
   -  Create a rule from selection (follow various paths from dropdowns
   e.g. cancel create, only enter some values, etc)
   -  Disable all rules
   -  Disable global rules
   -  DIsable local rules
   -  Enable all rules
   -  Enable workspace rules
   -  Enable global rules

*Commands Only (Ctrl + P, type grepc) *

Nothing pops up for me, just a message that says no "No matching results"

   -  Check release notes page

**Comment by cheljur** [comment]
Looking good, just wondering if this is the right order of priority? Lower on top, higher on the bottom? Seems counter intuitive.
image

**Comment by cheljur** [comment]
file exclude isn't working

**Pull request merged**
